CREATE database DB_PROJETO;

USE DB_PROJETO;

CREATE TABLE TB_STATUS_CONTA(
	ID BIGINT(10) NOT NULL
	, NOME VARCHAR(50)
	, PRIMARY KEY (ID)
);

INSERT INTO TB_STATUS_CONTA (ID, NOME) VALUES (1, 'Ativa'), (2, 'Cancelada'), (3, 'Bloqueada');

CREATE TABLE TB_PESSOA(
	ID BIGINT(10) NOT NULL AUTO_INCREMENT
	, TIPO_PESSOA BIT DEFAULT 0
	, CPF_CNPJ VARCHAR(14) NOT NULL
	, NOME VARCHAR(200) 
	, RAZAO_SOCIAL VARCHAR(200)
	, DATA_NASCIMENTO DATE 
	, PRIMARY KEY (ID)
);

CREATE TABLE TB_CONTA(
	ID  BIGINT(10) NOT NULL AUTO_INCREMENT
	, ID_PESSOA BIGINT NOT NULL
	, FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID)
	, ID_STATUS_CONTA BIGINT(10) NOT NULL 
	, FOREIGN KEY (ID_STATUS_CONTA) REFERENCES TB_STATUS_CONTA(ID)
	, ID_CONTA_PAI BIGINT(10)
	, FOREIGN KEY (ID_CONTA_PAI) REFERENCES TB_CONTA(ID) 	
	, SALDO DOUBLE NOT NULL DEFAULT 0
	, PRIMARY KEY (ID)
);


CREATE TABLE TB_TRANSACAO(
	ID BIGINT(10) NOT NULL AUTO_INCREMENT
	, ID_CONTA_DESTINO BIGINT(10) NOT NULL
    , FOREIGN KEY (ID_CONTA_DESTINO) REFERENCES TB_CONTA(ID)
	, ID_CONTA_REMETENTE BIGINT(10)
    , FOREIGN KEY (ID_CONTA_REMETENTE) REFERENCES TB_CONTA(ID)
	, VALOR DOUBLE NOT NULL
	, DATA_SOLICITACA DATETIME NOT NULL
	, ID_PESSOA BIGINT(10) NOT NULL
	, FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID) 
	, PRIMARY KEY (ID)
);

CREATE INDEX index_ID_CONTA_DESTINO ON TB_TRANSACAO(ID_CONTA_DESTINO);
CREATE INDEX index_ID_CONTA_REMETENTE ON TB_TRANSACAO(ID_CONTA_REMETENTE);



-- TRIGGER PARA ALTERAR O SALDO NAS TRANSACOES
DELIMITER $$
USE `DB_PROJETO`$$
CREATE TRIGGER `DB_PROJETO`.`TB_TRANSACAO_AFTER_INSERT` AFTER INSERT ON `TB_TRANSACAO` FOR EACH ROW
BEGIN
	IF EXISTS (SELECT * FROM INSERTED WHERE ID_CONTA_REMETENTE IS NOT NULL ) THEN
		UPDATE  TB_CONTA
		SET SALDO = SALDO - NEW.VALOR 
		WHERE ID = NEW.ID_CONTA_REMETENTE;
	END IF;
	
	UPDATE  TB_CONTA
	SET SALDO = SALDO + NEW.VALOR 
	WHERE ID = NEW.ID_CONTA_DESTINO;
END$$
DELIMITER ;
