CREATE database DB_PROJETO;

USE DB_PROJETO;

CREATE TABLE TB_STATUS_CONTA(
	ID BIGINT(10) NOT NULL
	, NOME VARCHAR(50)
	, PRIMARY KEY (ID)
);

INSERT INTO TB_STATUS_CONTA (ID, NOME) VALUES (1, 'Ativa'), (2, 'Cancelada'), (3, 'Bloqueada');

CREATE TABLE TB_PESSOA(
	ID BIGINT(10) NOT NULL AUTO_INCREMENT
	, TIPO_PESSOA BIT DEFAULT 0
	, CPF_CNPJ VARCHAR(14) NOT NULL
	, NOME VARCHAR(200) 
	, RAZAO_SOCIAL VARCHAR(200)
	, DATA_NASCIMENTO DATE 
	, UNIQUE(CPF_CNPJ)
	, PRIMARY KEY (ID)
);

CREATE TABLE TB_CONTA(
	ID  BIGINT(10) NOT NULL AUTO_INCREMENT
	, ID_PESSOA BIGINT NOT NULL
	, FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID)
	, ID_STATUS_CONTA BIGINT(10) NOT NULL 
	, FOREIGN KEY (ID_STATUS_CONTA) REFERENCES TB_STATUS_CONTA(ID)
	, ID_CONTA_PAI BIGINT(10)
	, FOREIGN KEY (ID_CONTA_PAI) REFERENCES TB_CONTA(ID) 	
	, SALDO DECIMAL(10,2) NOT NULL
	, NUMERO_CONTA VARCHAR(10) NOT NULL
	, UNIQUE(NUMERO_CONTA)
	, PRIMARY KEY (ID)
);


CREATE TABLE TB_TRANSACAO(
	ID BIGINT(10) NOT NULL AUTO_INCREMENT
	, ID_CONTA_DESTINO BIGINT(10) NOT NULL
    , FOREIGN KEY (ID_CONTA_DESTINO) REFERENCES TB_CONTA(ID)
	, ID_CONTA_REMETENTE BIGINT(10)
    , FOREIGN KEY (ID_CONTA_REMETENTE) REFERENCES TB_CONTA(ID)
	, VALOR DECIMAL(10,2) NOT NULL
	, DATA_TRANSACAO DATETIME NOT NULL
	, FLAG_APORTE BIT DEFAULT 0
	, CODIGO_ESTORNO_APORTE VARCHAR(10)
	, DATA_ESTORNO DATETIME
	, PRIMARY KEY (ID)
);

CREATE INDEX index_ID_CONTA_DESTINO ON TB_TRANSACAO(ID_CONTA_DESTINO, ID_CONTA_REMETENTE);

DELIMITER //
CREATE PROCEDURE getFiliaisFrom(IN idRemetente BIGINT(10))
 BEGIN
	select t.id as item_id, @pv:=t.ID_CONTA_PAI as parent
	from (select * from TB_CONTA order by id desc) t
	join
	(select @pv:=idRemetente)tmp
	where t.ID_CONTA_PAI=@pv; END //
DELIMITER ;